### ISSUE TITLE
Please add comparison to cerebro

### ISSUE THREAD

**Issue by xrl** [cars10/elasticvue#1]
We have gone through many ES interaction tools, the overall movement was

head -> kopf -> cerebro

Can you compare your tool to cerebro? It's from the same author as kopf. It's very good.

**Comment by cars10** [comment]
Yes. The main reason why i wrote elasticvue is because i needed a way to browse huge amounts of documents in my cluster. I did not need a gui to "manage" my cluster (e.g. change mappings or other settings) but rather a tool to view/search the documents (think something like mysql-workbench or sequel pro but for elasticsearch). 

As far as i know this is not possible with cerebro, at least i did not find an option for that. Thats what i liked in head - but it only displays 50 documents and does not have pagination, filters or anything else.

I will add cerebro to the list of compared tools in the readme, thanks for the hint.

**Comment by xrl** [comment]
Cerebro lets you do raw REST calls to the cluster and it has a little bit of a history for past queries. But you're right, cerebro is not document oriented but rather cluster oriented.

**Comment by cars10** [comment]
Yes, thats right. But i think a table is a much better way to have an overview of your documents. 

PS: Elasticvue also lets you to REST calls manually ("Query" in the navbar)

**Comment by cars10** [comment]
Fixed via 402eb40
