### ISSUE TITLE
[BUG] - I can't use elasticvue,when the xpack is OPEN.

### ISSUE THREAD

**Issue by Byc4i** [cars10/elasticvue#109]
**READ BEFORE OPENING AN ISSUE**
Before you submit an issue please try to reset elasticvue and see if you can reproduce the problem.
To reset please click `Disconnect and reset` in the footer, this will reset all your saved filters and you have to reconnect to your cluster.
Proceed and open an issue if your problem persists.

**Description**
Please describe your problem here.

**Steps To Reproduce**
how do I input my elastic/password ?

**Screenshots**

**Environment (please include the following information):**
* Elasticsearch version:
* Operating system:
* Browser + version:
* Elasticvue version:
* How are you running elasticvue? (docker, browser extension, web app):

browser extension

**Additional context**

**Comment by cars10** [comment]
When you open elasticvue you should see this screen:

![image](https://user-images.githubusercontent.com/4118628/183409589-6683cc77-b693-47d0-91d4-52e6b6eff37f.png)

You can enter username+password directly there. I am not sure where the issue is, please reopen and provide additional information if your issue persists :)
