### ISSUE TITLE
[FEAT] ability to configure the docker image to be pre-populated with clusters

### ISSUE THREAD

**Issue by cemeyer2** [cars10/elasticvue#112]
**Description**
When launching the docker container, it would be nice to be able to supply environment variables to instruct elasticvue to launch already provisioned. An example use case would be running elasticsearch in docker compose and adding elasticvue to the compose file. In this scenario, the cluster endpoints are known and it would be great to be able to pass them into elasticvue.

**Comment by cars10** [comment]
This will be fixed in the next version. You can provide clusters via environment variable or config file. Users will be able to import the clusters that you provided:

![image](https://github.com/cars10/elasticvue/assets/4118628/167d5430-2b1e-48a2-a487-1fef3ab987cf)
![image](https://github.com/cars10/elasticvue/assets/4118628/db2aefb8-ef02-4fc4-8d0f-bb076edee467)


You can also import the clusters at a later stage, e.g. when the config was updated with new clusters:
![image](https://github.com/cars10/elasticvue/assets/4118628/f1ce367c-2a63-40a6-9a32-58906ef2433d)
