### ISSUE TITLE
[BUG] - Scrolling is wonky with sticky header row

### ISSUE THREAD

**Issue by bengaywins** [cars10/elasticvue#124]
**Description**
When using a sticky header row in the indices tab, there are in effect two areas to scroll. This makes it a bit wonky as it makes you need to scroll the list and the entire page.

**Steps To Reproduce**
List the steps to reproduce your problem:
1. Open elasticvue
2. Click on indices
3. Ensure sticky header row is enabled
4. Show more than one page of indices
5. Scroll the indices

**Screenshots**
https://imgur.com/a/TeaoT4a

**Environment (please include the following information):**
* Elasticsearch version: 7.2.0
* Operating system: macOS 12.6.1
* Browser + version: FF 106.0.5
* Elasticvue version: 0.43.0
* How are you running elasticvue? (docker, browser extension, web app): Browser extension

**Comment by cars10** [comment]
Its not a bug, its a  feature :) If you enable "sticky header" then you have to scroll inside the table, this is the logical thing to do. What else would "sticky header" do? :)  Because the page contains more then just the table contents (header, footer, pagination, etc) there is no other way to solve this. In my opinion this is an issue in macos, because you cannot even see the scrollbars.

But you can always disable "sticky header" to have a uniform scrolling experience.
