### ISSUE TITLE
[FEAT] 请问 docker 部署模式是否可以考虑 反代 elasticsearch 的实际地址呢？

### ISSUE THREAD

**Issue by xjdata** [cars10/elasticvue#130]
**Description**

 请问 docker  部署模式是否可以考虑 反代 elasticsearch 的实际地址呢？

 为杜绝隐患，不希望开放elasticsearch的端口。

实现类似 kibana 无需设置 elasticsearch 的效果。 

谢谢。

**Comment by cars10** [comment]
Hey, sorry i do not speak any asian language and google translate is spitting out nonsense. Can you translate your issue to english please?

**Comment by xjdata** [comment]
sorry about  topic language

------


I don't want to open port 9200 of elasticsearch.

Like kibana no need to setup elasticsearch.

Can the service in the elasticvue docker image reverse the actual address of elasticsearch?


thanks.

**Comment by cars10** [comment]
Hi, sadly this is not possible.

1. You *have* to "open" port 9200, how else would any service (kibana, elasticvue, or your own application) communicate with elasticsearch :)
2. kibana is a native application that is not subject to the same limitations that elasticvue as a web based application is. because elasticvue runs in the browser you have to configure CORS if you want to use elasticvue as a docker image or website. Use the browser addons or the desktop version if you dont want to or cannot configure cors
