### ISSUE TITLE
[BUG] - Not connected

### ISSUE THREAD

**Issue by EvgeniyMakhmudov** [cars10/elasticvue#14]
**Description**
Do not connect to ES. Try to use extansion in FF and Chrome, result the same. 

**Steps To Reproduce**
List the steps to reproduce your problem:
1. Open elasticvue
2. Click on Test connection
3. GET request sended, recieve response with status 200 with standard greeting message from ES in body.

**Screenshots**
![ES](https://user-images.githubusercontent.com/3597681/75027693-0c909280-54b0-11ea-9a37-96ab5adf3d1e.png)

**Environment (please include the following information):**
* Operating system: Linux Mint 19.2
* Browser + version: FireFox 72, Chrome 70
* Elasticvue version: 0.18.0
* How are you running elasticvue? (docker, chrome extension, web app): firefox and chrome extension

**Additional context**
using another tools like elasticsearch-head extension work properly.

**Comment by cars10** [comment]
Hey, i'm sorry that you have issues with elasticvue. Can you please answer some follow up questions?

1. Did elasticvue work for you in the past or did you just start to use it?
2. Are you sure that you have correctly configured your `cors` setting in `elasticsearch.yml`? Maybe you only allow acces to elasticsearch-head

Thanks

**Comment by EvgeniyMakhmudov** [comment]
Thanks for quick response.

1) I try use it first time
2) i do not set any CORS settings, ES used as docker container from official image, and only do is make ports public. Right now the config is 
```
bash-4.4# cat config/elasticsearch.yml 
http.host: 0.0.0.0

# Uncomment the following lines for a production cluster deployment
#transport.host: 0.0.0.0
#discovery.zen.minimum_master_nodes: 1
```

 It work with simple curl request  
```
curl http://localhost:9200
{
  "name" : "MdOpyc7",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "dW43VmLsTQKXK7jrv7SjxQ",
  "version" : {
    "number" : "5.6.5",
    "build_hash" : "6a37571",
    "build_date" : "2017-12-04T07:50:10.466Z",
    "build_snapshot" : false,
    "lucene_version" : "6.6.1"
  },
  "tagline" : "You Know, for Search"
```

If any question about this, you are welcome

**Comment by cars10** [comment]
Thanks. Your problem is that you did not enable `cors` in your elasticsearch, this is needed to communicate with elasticvue in the browser. To do so you need to add the setting to your elasticsearch.yml as is described on the setup page on your screenshot (the first step, "1. Configure").

If you want to start your elasticsearch cluster via docker then you can also enable cors via environment variables, like so:

```
docker run -p 9200:9200 \
                  -e "http.cors.enabled=true" \
                  -e "http.cors.allow-origin=/.*/" \
                  -e "discovery.type=single-node" \
                  docker.elastic.co/elasticsearch/elasticsearch:5.6.5
```

**Comment by EvgeniyMakhmudov** [comment]
I try as you say to run docker container with cors. But the situation the same. In this case GET request receive response with Basic Auth. I see it elasticsearch-head, curl. elasticvue make analog request and response but it still says that cant connect.

**Comment by EvgeniyMakhmudov** [comment]
Anyway, i want try use elasticvue to understand is it support work with https protocol with ignore ssl verify (like curl with option `-k`) . elasticsearch-head cant do https request.
Is it possible with elasticvue?

**Comment by cars10** [comment]
If you want to skip certificate verification then you have to import your CA certificate into the browser. Elasticvue uses the browsers API's to query your cluster so it depends on the browser to trust the certificate.

You can use elasticvue with an elasticsearch cluster that uses ssl and authorization. An Example:

- Follow the [official guidelines](https://www.elastic.co/guide/en/elasticsearch/reference/current/configuring-tls-docker.html) for a basic elasticsearch docker setup with certificates
- Add the following lines to the `environment` section in the `docker-compose.yml`:

```
      - http.cors.enabled=true
      - http.cors.allow-origin=/.*/
      - http.cors.allow-headers=X-Requested-With,Content-Type,Content-Length,Authorization
```

- Follow the steps to create your certificate and start your cluster
- In elasticvue, enter the following as your url: `https://elastic:PleaseChangeMe@localhost:9200`

If the browser does not trust your CA then you will now get a certificate error in your console. There are three ways to fix that:

1. Import the CA so that your browser trusts it
2. Use an already trusted CA (like letsencrypt)
3. Simply bypass the error temporarily by entering [https://elastic:PleaseChangeM@localhost:9200](https://elastic:PleaseChangeM@localhost:9200) in your browser and clicking "Proceed to <url> (unsafe)". This way the browser will trust the certificate for your current session and you can also use elasticvue.

**Comment by cars10** [comment]
@EvgeniyMakhmudov i am closing this issue for now because of inactivity. Feel free to reopoen (or open a new issue) if you still have a problem with elasticvue.

**Comment by EvgeniyMakhmudov** [comment]
i already typed big message)

**Comment by cars10** [comment]
Sorry, i thought i had answered all your questions above. Did you try to setup your cluster as i mentioned in [https://github.com/cars10/elasticvue/issues/14#issuecomment-589759276](https://github.com/cars10/elasticvue/issues/14#issuecomment-589759276) ?

**Comment by EvgeniyMakhmudov** [comment]
So, i return for this question. 
Ok, i try to be shorter. If i configure my local ES docker container with CORS support via config file, then elasticvue working. It is good.
But why elastichead extension work without CORS configuration? I found some answer in GH page of [ElasticSearch Head add-on for Firefox](https://github.com/barseghyanartur/elasticsearch-head-firefox#motivation). Maybe it can be possible to do the same with elasticvue? 
To simulate avoid this i use nginx as proxy, and elasticvue working good without CORS configurating.
> It also has the advantage of bypassing CORS without configuring CORS on your Elastic server.

**Comment by cars10** [comment]
Thanks for clarifying your question :)

The elasticsearch-head extension for firefox (and chrome) works without configuring CORS because you give them permission to intercept _every_ request you make to any website in your browser.

See [these lines](https://github.com/barseghyanartur/elasticsearch-head-firefox/blame/master/manifest.json#L21-L22) in the extension manifest and [the explanation](https://developer.chrome.com/extensions/xhr#requesting-permission) by google. 
I am not happy with granting my extension permissions to request any remote server and completely bypass CORS because:

- CORS is a great security measure
- I wanted the users of elasticvue to have a unified experience when using it. There are many ways to run elasticvue (multiple browser extensions, docker container, hosted on the website, etc) and it would be weird if one of them can work out of the box (browser extension) and you have to configure CORS for the others.

I will think about adding an exception for local clusters by using permissions like this:

```
  "permissions": [
    "http://localhost/*",
    "https://localhost/*"
  ],
```

so you could at least use the extension without configuring CORS **if** you use a local cluster, but for anything not reachable via `localhost` you will most likely still have to configure CORS.

Thanks!

**Comment by honza-zidek** [comment]
I think it is a logical error in the logic of how the browsers treat the plugins. They should consider requests coming from your browsers as requests from `localhost`!!! When I request the same page directly from the browser, there is no CORS issue!
