### ISSUE TITLE
[BUG] - Sorting and Pagination are not working when returned back to the same page.

### ISSUE THREAD

**Issue by deepakdaneva** [cars10/elasticvue#144]
**Description**
Sorting and Pagination are not working when the user returns back to the same page after applying pagination and sorting.

**Steps To Reproduce**
List the steps to reproduce your problem:
1. Open elasticvue
2. Go to the Search page
3. If records are getter than 10 then select pagination size as 20
4. Also select the specific sorting on a date field (not tried on any other field type)
5. Once the results are fetched go to any other page let's say REST
6. Then return back to the previous page where we were searching.
7. Notice that sorting is not proper and also even if 20 page size was selected there are only 10 records in the grid.

**Screenshots**

Sorting:
![image](https://github.com/cars10/elasticvue/assets/68489729/bfbade31-7629-4a32-8a2a-0096bac32f09)

Pagination:
![image](https://github.com/cars10/elasticvue/assets/68489729/300967b0-2252-45b9-856f-b4715d6f447f)

**Environment:**
* Elasticsearch version: 7.16.3
* Operating system: Windows 11
* Browser + version: Brave Version 1.51.118 Chromium: 113.0.5672.126 (Official Build)  (64-bit)
* Elasticvue version: 0.44.0
* How are you running elasticvue? (docker, browser extension, web app): Browser Extension

**Comment by aka-Ani** [comment]
Hmm I'm unable to reproduce with those steps on 0.44.0 Firefox. The two screenshots seem to be of different indices? At which point did you change the index? Because I am sort of able to "reproduce" this if I go to the Indices page after performing a size 20 search, then clicking on a different index, now the search page query defaults back to size 10 but the dropdown GUI at the bottom for "Rows per page" still shows 20.

The other thing that would be helpful is expanding the "custom search" button to see the full query. Any time you click a column to sort or change the rows per page, that raw query json should update to reflect the change

**Comment by cars10** [comment]
I also cannot reproduce this issue. Please open again if you still encounter it with beta2 https://github.com/cars10/elasticvue/releases/tag/v1.0.0-beta-2

**Comment by Vaggal** [comment]
I have noticed this problem also

Environment:
    Elasticsearch version: 7.17.7
    Operating system: Windows 10
    Browser + version: Firefox 124.0.2
    Elasticvue version: 1.0.4
    How are you running elasticvue? (docker, browser extension, web app): Browser Extension
