### ISSUE TITLE
[FEAT] - Add a prompt box for secondary confirmation for sensitive operations

### ISSUE THREAD

**Issue by XiangtingLee** [cars10/elasticvue#153]
Some sensitive operations for Index are easy to misuse. It is hoped that a secondary confirmation prompt box similar to Cerebro can be added for Index operations.

![image](https://github.com/cars10/elasticvue/assets/26403302/c4dcc665-cd42-4231-9a51-dee613f41acf)

In Cerebro:
![image](https://github.com/cars10/elasticvue/assets/26403302/ad172ab4-06f3-48e0-aecb-f210490f483a)

**Comment by cars10** [comment]
Hey @XiangtingLee , thanks for using elasticvue :) Deleting an index already requires a confirmation. I do not consider forcemerge, refresh, flush or index clear to be a sensitive operation because all of these happen automatically anyway.
Opening and closing is debateable i guess - i will think about that :)

**Comment by cars10** [comment]
Added a confirm message for closing indices, will be released with the upcoming beta 6.
