### ISSUE TITLE
Access your data for all websites???

### ISSUE THREAD

**Issue by oshanz** [cars10/elasticvue#18]
![image](https://user-images.githubusercontent.com/5364479/77824437-a63f0580-7128-11ea-8b40-43e4e75dc68e.png)

I'm seen this message. is this from a recent change? is it safe? I have disabled the extension but message is still popping up.

**Comment by cars10** [comment]
Hi, thanks for reaching out. Elasticvue needs this permission to make requests to your elasticsearch cluster without cors restrictions. Because I cannot know the URL of your cluster I have to requests permission to all URLs.

The message you see is just the browsers way of asking for these permission. Elasticvue does not actually read any data of any websites that you visit, and it will never do that. You are free to check the sourcecode and/or build elasticvue manually to make sure.

Check out 
https://github.com/cars10/elasticvue/pull/17 for more information and discussion about this change. 

Ps: this is something most elasticsearch extensions do, for example elasticsearch-head.
