### ISSUE TITLE
Allow mTLS connections to ES

### ISSUE THREAD

**Issue by tmegow** [cars10/elasticvue#33]
While dismissing the feature request described in [Issue #32](https://github.com/cars10/elasticvue/issues/32) as a Bug Report, half the Feature Request was ignored.

TLS
—
I stupidly thought the -k option on curl would make the request transparent but I should have provided more clarifying info. You’ve offered that there is no way to supply overridden/custom certs in a Chrome, Edge, Firefox extensions. I did some simple research (as a green browser extensions dev) on the topic and I see these extension API features, do these allow supplying custom certs? If feasible, please allow us to supply self-signed certs using these extension features and allow us to connect to ES using self-signed certs.
[WebExtensions API - SecurityInfo](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/SecurityInfo) [Chrome Extensions API - certificateProvider](https://developer.chrome.com/extensions/certificateProvider) 

mTLS
—
[See xpack.security.transport.ssl.client_authentication and xpack.security.http.ssl.client_authentication](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-settings.html#ssl-tls-settings) 

Does ElasticVue allow mTLS using client certificates? If not please allow us to connect to ES using x509 certs for authentication.

**Comment by cars10** [comment]
Hey, sorry for overseeing your question regarding mTLS / client certificates in general. I have some questions regarding this feature request:

1. I am not quite sure how these certificates are used. Would you expect the browser to show a built-in popup where you can select a preinstalled certificate our do you need a file selection button to "upload" the actual certificate from your local filesystem?
2. Did you try the third solution i proposed in [#32](https://github.com/cars10/elasticvue/issues/32#issuecomment-662855039)? It would be interesting to know if this could (temporarily) solve the problem.

Thanks!

**Comment by cars10** [comment]
Close for now, because I am still not sure how your setup looks like and what exact problem you want to solve. Please feel free to reopen this issue with additional details (and an example setup if possible).

**Comment by moesterheld** [comment]
@cars10 Since a colleague needed it, I added some basic mTLS / client authentication functionality to your reqwest wrapper. It reads the client certificate and the client's private key from environment variables or passed in from the frontend using custom headers (although this does pose some security risk and should not be done for production systems).
It would need some more work and a bit of cleaning, but if you're interested, we could discuss on how to proceed with it.
On an additional note, mTLS will probably never work for the browser extension, only for the desktop apps.

**Comment by cars10** [comment]
Dear @moesterheld , thank you for taking the time to work on this.

> mTLS will probably never work for the browser extension, only for the desktop apps.

If this is indeed the case then i am very hesitant to implement this feature. Up until now every feature in elasticvue is available in all of its versions and i really want to keep it that way to avoid confusion. But as far as i am aware you should be able to import certificates into the browsers certificate store and select those when working with mtls?

**Comment by moesterheld** [comment]
Let me clarify this. mTLS will (and already does) work for the browser extension if the server actively asks for it.
I don't know the setting for Elasticsearch, but for Opensearch, this is `plugins.security.ssl.http.clientauth_mode=REQUIRE`.

In this case, the client certificate and private key can be stored in the system keystore and the browser will ask for a certificate when a call to the search server is made, because during the handshake, the server asks for a client certificate. This also works in the extension, I just tried that.

However, if you have this as optional (our use case) or want to provide the certificate directly on the cluster configuration page, this won't work as you cannot have control over how the browser does mTLS.

This was the reason why I baked it into reqwest, similar to how you allow self-signed certificates there. I moved the option to provide a client certificate behind the `buildConfig.tauri` flag.

But I understand you completely if you don't want to have different capabilities between the different versions.
