### ISSUE TITLE
[FEAT] Simple Proxy backend to avoid setting cors on elasticsearch server

### ISSUE THREAD

**Issue by adityaU** [cars10/elasticvue#34]
**Description**
Thanks for the development of this tool. Can you please provide a simple Proxy backend to avoid setting cors on elasticserver. I don't have access to chrome (iPad connected to remote server) and can not allow setting up cors on elasticsearch server. 

**The feature is similar to..**
Does the feature exist in a similar tool (for example `kibana`)? If so, please:
* https://github.com/lmenezes/cerebro
* iPad connected to remote server. Elasticvue is running in a docker container. access elasticvue via safari

**Additional context**
Anything else?

**Comment by cars10** [comment]
Hi, sadly you have to setup CORS because elasticvue is running completely in the browser. Also the whole reason CORS exists is that you can only query servers that you have access to.

Providing a seperate backend (like cerebro) would result in a complete rewrite of elasticvue. Right now it is specifically built to run in the browser with no server component whatsoever.

If you need a proxy to bypass CORS you can do that yourself, for example with an nginx container.
An (untested) example nginx config could look like this:

```
server {
        listen 9000;
        add_header 'Access-Control-Allow-Origin' '*';

        location / {
            proxy_pass http://your.cluster.ip:9200;
        }
    }
```

**Comment by cars10** [comment]
Hi @adityaU , you might be interested in [simprox](https://github.com/cars10/simprox). It should do exactly what you need.
