### ISSUE TITLE
Support SSL certificate

### ISSUE THREAD

**Issue by mrksoftware** [cars10/elasticvue#48]
Hi all,
In order to connect to my customer's ES server I need to associate an SSL certificate.
This has been provided via a pfx certificate.
Just to give you an example in Postman this is possible through the `Certificates` menu:

![image](https://user-images.githubusercontent.com/7292153/105717575-96e34100-5f20-11eb-978a-b7aabe6aab12.png)

Is it possible to add this feature? This is the only thing which is preventing me from using this fantastic tool! 😊 
Thanks in advance!

**Comment by cars10** [comment]
It is possible to access an SSL protected cluster. Try one of the following ways:

1. Simply add the certificate to your browsers/os certificate store
2. Use a trusted certificate authority so your browser will accept it automatically
3. When connecting to elasticvue, and it shows the red error message, click on the link to your cluster in the text (see screenshot below). Your browser will warn you about your untrusted certificate. Trust the certificate, go back to elasticvue and you are good to go. You have to do that every time you reopen your browser, because trusting an untrusted certificate only lasts for the current session.

![image](https://user-images.githubusercontent.com/4118628/105718491-9303ee80-5f21-11eb-8e3c-c737723a8c69.png)

**Comment by cars10** [comment]
I know that this is not very convenient, but sadly these are the only options (that i am aware of). Because elasticvue runs completely in the browser it has to rely on the browser trusting the certificate. If the browser does not trust it then i cannot bypass that.

**Comment by mrksoftware** [comment]
Oh, I don't know why I didn't thought about it! 😄 

That's more than enough! Thank you for the prompt response!
By installing the certificate in my browser (I already did that for the OS but it was not sufficient) I was able to access!
Thank you very much! 👍

**Comment by cars10** [comment]
Awesome, glad that you made it work :)

I have also added this information to the [Wiki](https://github.com/cars10/elasticvue/wiki/Access-clusters-using-SSL) for future reference.
