### ISSUE TITLE
Chrome Webstore link is not available

### ISSUE THREAD

**Issue by mdegrugilliers** [cars10/elasticvue#51]
The extension on Chrome Webstore is no more accessible : 404.
https://chrome.google.com/webstore/detail/elasticvue/hkedbapjpblbodpgbajblpnlpenaebaa

Can you restore it. Thanks

**Comment by cars10** [comment]
Hey, thank you for opening this issue.
Yesterday google decided to remove elasticvue from the store because of reasons. I have already submitted a new version and hope that is is available soon, right now it is still awaiting a review.

In the meantime you can manually install the chrome addon (you can download the zip from [here](https://github.com/cars10/elasticvue/releases/tag/v0.33.0) or use firefox/edge until google enables the addon again.

Sorry for the inconvenience!

**Comment by cars10** [comment]
Elasticvue is available again on the chrome web store.
