### ISSUE TITLE
[BUG] - Long numbers being parsed wrong 

### ISSUE THREAD

**Issue by bgrgv** [cars10/elasticvue#52]
When displaying long numbers in Elasticvue, it rounds off to the nearest even number. 

For example, the number 74897271582524117 gets displayed as 74897271582524116

**Steps To Reproduce**
1. Open elasticvue
2. Load any row that has a long number

**Environment**
* Elasticsearch Version : 7.10.2
* Windows 10
* Chrome
* Elasticvue version : 0.33.0
* How are you running elasticvue : extension

**Comment by cars10** [comment]
Hey, thanks for using elasticvue and opening this issue. I can reproduce this, i will look into it.

**Comment by cars10** [comment]
Sadly this seems to be a javascript issue, because javascript cannot handle such big numbers:

![image](https://user-images.githubusercontent.com/4118628/115529156-f4262e80-a292-11eb-891c-3fd95a3e4897.png)

Maybe i can work around that but i am not sure yet.

**Comment by bgrgv** [comment]
Hey!
You could convert them to a String. API response from Elasticsearch will have the correct value.

**Comment by cars10** [comment]
True, but then it would not show correctly in the document view, for example here:
![image](https://user-images.githubusercontent.com/4118628/115543710-f9d74080-a2a1-11eb-985c-d9edf5cc964c.png)
would be confusing to see the number as a string when it is really a number.

**Comment by bgrgv** [comment]
Can we include this library to fix the issue?
https://github.com/MikeMcl/bignumber.js

**Comment by milesich** [comment]
Maybe this old issue can help you: https://github.com/elastic/elasticsearch-js/issues/648

**Comment by cars10** [comment]
Hey guys, thanks for the links. Sadly i think that i cannot fix this. The main issue is, that calling `.json()` on the fetch response already returns the "wrong" result. There is no point where i can hook into to change the handling of the numbers. 

Because elasticvue runs completely in the browser i can only rely on fetch and the browsers capabilities.

Check out the following example where i fetch a document that includes a big number. Loading the text response is fine, but loading it a json (thats what we need to show the data in the table for example) returns the wrong number.

![image](https://user-images.githubusercontent.com/4118628/115838738-4776b900-a41a-11eb-98b0-122e80bd1c8b.png)

I think the only solution to this issue is to index numbers this large as strings. I know this is not really a solution, but because this is a javascript limitation you will likely have the same issue in kibana and similar elasticsearch frontends (and possibly in other languages/tools where you use this data)


Apart from that, may i ask what data you are indexing with numbers this large? This obviously wont help with the issue, just curious :)

**Comment by bgrgv** [comment]
In my case, it's a combination ID, for example, entity A has an ID 345 and entity B has an ID 254, then the combination ID would be 345254. This is critical for data processing, and is coming from RDBMS. Elasticsearch just has a clone of the data. 

Also, I've run into major confusions due to this bug. In my opinion, showing it as a string with some indications, like a colour change, or appended data type or similar could help. I feel that correct value should be weighed over correct datat type if a trade off has to be made.

**Comment by cars10** [comment]
> Also, I've run into major confusions due to this bug.

Yea, i can imagine the issues this bug might cause, sorry for that. It seems that i can manually parse the json with https://github.com/sidorares/json-bigint , i will try this on the weekend and see if that fixes it!

**Comment by bgrgv** [comment]
Not of an issue, after all, Elasticvue is an awesome tool, right from the browser :)

**Comment by cars10** [comment]
Hey @bgrgv , i am happy to tell you that i have fixed this issue. Big numbers should now "just work" like smaller ones. Keep in mind though that i don't know how other tools (and elasticsearch itself) handle these numbers, stuff like sorting or searching for example might not work as expected.

I plan to release a new version of elasticvue in the following week. It would be great if you could test the new version prior to the release to validate if your issues are indeed fixed. I have attached an updated chrome extension for you to try if you may :)
[elasticvue-0.33.0-chrome-big-number-fix.zip](https://github.com/cars10/elasticvue/files/6371778/elasticvue-0.33.0-chrome-big-number-fix.zip)

**Comment by bgrgv** [comment]
Awesome!
I'll check it and update here. How'd you fix it?

**Comment by cars10** [comment]
I no longer use the `.json()` function on fetch responses, i have replaced these with `.text()` to get the plain text response. Then i use `json-bigint` to manually parse that into json. Needed a few more adjustments here and there, but thats the main part

**Comment by cars10** [comment]
ping @bgrgv :) Did you have time to try the new version yet?

**Comment by cars10** [comment]
Added this feature in `0.34.0`. I still think that you should index numbers this large (that are not intended for calculation) as string because you will likely face similar issues in other languages/frameworks, but elasticvue does support them now :)

**Comment by bgrgv** [comment]
Awesome!
I agree with your suggestion, but this is one particular project where we
can't get that done due to the size of existing ecosystem.
